name: CI
on:
  push:
    branches:
      - main
      - feat/*
    tags:
    - v*
    
  pull_request:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
        shell: bash

  sonarcloud:
    uses: redpanda/workflows/.github/workflows/code-quality.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
